filter:
  excluded_paths: [tests/*]

checks:
  php:
    code_rating: true
    duplication: true
    remove_extra_empty_lines: true
      remove_php_closing_tag: true
      remove_trailing_whitespace: true
      fix_use_statements:
        remove_unused: true
        preserve_multiple: false
        preserve_blanklines: true
        order_alphabetically: true
      fix_php_opening_tag: true
      fix_linefeed: true
      fix_line_ending: true
      fix_identation_4spaces: true
      fix_doc_comments: true
tools:
  php_analyzer: true
  php_mess_detector: true
  php_changetracking: true
  php_code_sniffer:
    config:
      standard: PSR2
  php_loc:
    excluded_dirs:
      - vendor
  php_pdepend:
    excluded_dirs:
      - vendor
      - tests
  external_code_coverage: true
build:
  environment:
    php:
      version: 7.2       # Common versions: 5.4, 5.5, 5.6, 7.0, 7.1, or hhvm

